apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-sync-frontend
  labels:
    app: video-sync-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-sync-frontend
  template:
    metadata:
      labels:
        app: video-sync-frontend
    spec:
      containers:
      - name: video-sync-frontend
        image: video-sync-frontend
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: video-sync-frontend
spec:
  selector:
    app: video-sync-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80